/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KeyboardAccessibilityRouteImport } from './routes/keyboard-accessibility'
import { Route as IndexRouteImport } from './routes/index'

const KeyboardAccessibilityRoute = KeyboardAccessibilityRouteImport.update({
  id: '/keyboard-accessibility',
  path: '/keyboard-accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/keyboard-accessibility': typeof KeyboardAccessibilityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/keyboard-accessibility': typeof KeyboardAccessibilityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/keyboard-accessibility': typeof KeyboardAccessibilityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/keyboard-accessibility'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/keyboard-accessibility'
  id: '__root__' | '/' | '/keyboard-accessibility'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KeyboardAccessibilityRoute: typeof KeyboardAccessibilityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/keyboard-accessibility': {
      id: '/keyboard-accessibility'
      path: '/keyboard-accessibility'
      fullPath: '/keyboard-accessibility'
      preLoaderRoute: typeof KeyboardAccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KeyboardAccessibilityRoute: KeyboardAccessibilityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
